import Testing
import Foundation
import Crypto
@testable import SwiftKeyGen

@Suite("HMAC Compatibility Tests")
struct HMACCompatibilityTests {
    
    // Helper functions
    func generateHashWithSpecificSalt(hostname: String, salt: Data) -> String {
        let hostData = Data(hostname.utf8)
        let hmac = HMAC<Insecure.SHA1>.authenticationCode(for: hostData, using: SymmetricKey(data: salt))
        return "|1|\(salt.base64EncodedString())|\(Data(hmac).base64EncodedString())"
    }
    
    func parseHashedEntry(_ entry: String) -> (salt: Data, hash: Data)? {
        let components = entry.split(separator: "|")
        guard components.count >= 3,
              components[0] == "1",
              let salt = Data(base64Encoded: String(components[1])),
              let hash = Data(base64Encoded: String(components[2])) else {
            return nil
        }
        return (salt, hash)
    }
    
    func verifyHashedHost(_ hashedPattern: String, hostname: String) -> Bool {
        guard let (salt, expectedHash) = parseHashedEntry(hashedPattern) else {
            return false
        }
        
        // Compute HMAC for hostname with given salt
        let hostData = Data(hostname.utf8)
        let hmac = HMAC<Insecure.SHA1>.authenticationCode(for: hostData, using: SymmetricKey(data: salt))
        
        return Data(hmac) == expectedHash
    }
    
    @Test("Verify ssh-keygen generated hashes")
    func testSSHKeygenHashVerification() throws {
        // These are actual hashes generated by ssh-keygen -H
        let sshKeygenHashes = [
            ("github.com", "|1|HaNPCCkur6qYZXCzIppl/TodLqw=|GgFFFoJPMiwE59VjqulA59RWQxc="),
            ("[example.com]:2222", "|1|MqPW9+kMObMEhin7KtSezLHs0qc=|RsILfjmyLGY39C38uK65QInDmMc="),
            ("192.168.1.1", "|1|O1R3WUmACW3NL3xeF5XWKf4PuhA=|Ro4TK7ueLhcepbg5rjnYDG4NL1c=")
        ]
        
        for (hostname, hash) in sshKeygenHashes {
            let verified = verifyHashedHost(hash, hostname: hostname)
            #expect(verified, "Failed to verify hash for \(hostname)")
        }
    }
    
    @Test("Generate and self-verify hashes")
    func testHashGenerationAndVerification() throws {
        let testCases = [
            "github.com",
            "example.com",
            "[example.com]:2222",
            "192.168.1.1",
            "*.example.com",
            "test-host.example.org",
            "localhost",
            "::1",
            "[::1]:22"
        ]
        
        for hostname in testCases {
            // Generate random salt
            let salt = Data((0..<20).map { _ in UInt8.random(in: 0...255) })
            let hash = generateHashWithSpecificSalt(hostname: hostname, salt: salt)
            let verified = verifyHashedHost(hash, hostname: hostname)
            #expect(verified, "Failed to self-verify hash for \(hostname)")
        }
    }
    
    @Test("Deterministic hash generation with fixed salt")
    func testDeterministicHashGeneration() throws {
        // Use a fixed salt for deterministic testing
        let fixedSalt = Data([
            0x1d, 0xa3, 0x4f, 0x08, 0x29, 0x2e, 0xaf, 0xaa,
            0x98, 0x65, 0x70, 0xb3, 0x22, 0x9a, 0x65, 0xfd,
            0x3a, 0x1d, 0x2e, 0xac
        ])
        
        let testCases = [
            ("test.example.com", "|1|HaNPCCkpLq+qhleDMimm/Tod4q0=|VxJmTUzgxzBWGmT8FW8QHcbhmL0="),
            ("localhost", "|1|HaNPCCkpLq+qhleDMimm/Tod4q0=|a6Qn7jdlVkqg7OwLI/0PQFKzNMw="),
            ("10.0.0.1", "|1|HaNPCCkpLq+qhleDMimm/Tod4q0=|Ec5vGhcNf1z+5+bDBYRJH/d5jSY=")
        ]
        
        for (hostname, expectedHash) in testCases {
            let hash = generateHashWithSpecificSalt(hostname: hostname, salt: fixedSalt)
            #expect(hash == expectedHash, "Hash mismatch for \(hostname)")
            
            // Verify we can parse and verify our own hash
            let verified = verifyHashedHost(hash, hostname: hostname)
            #expect(verified, "Failed to verify generated hash for \(hostname)")
        }
    }
    
    @Test("Verify specific ssh-keygen hash")
    func testSpecificSSHKeygenHash() throws {
        let hostname = "test.swiftkeygen.example"
        let sshKeygenHash = "|1|9lJeWLayTN6JX+REkjwXCryLpxM=|ErZ7D5Wf46EklpyWFhZsW4P9x5o="
        
        // Parse the hash
        guard let (salt, expectedHash) = parseHashedEntry(sshKeygenHash) else {
            Issue.record("Failed to parse hash")
            return
        }
        
        // Compute HMAC with SwiftKeyGen's method
        let hostData = Data(hostname.utf8)
        let hmac = HMAC<Insecure.SHA1>.authenticationCode(for: hostData, using: SymmetricKey(data: salt))
        let computedHash = Data(hmac)
        
        #expect(computedHash == expectedHash, "HMAC hash mismatch")
        
        // Generate the same format hash
        let ourHash = "|1|\(salt.base64EncodedString())|\(computedHash.base64EncodedString())"
        #expect(ourHash == sshKeygenHash, "Generated hash string mismatch")
    }
    
    @Test("Binary HMAC output verification")
    func testBinaryHMACOutput() throws {
        let testHost = "verification.test"
        let testSalt = Data("TestSaltForHMAC1234".utf8)
        
        let hostData = Data(testHost.utf8)
        let hmac = HMAC<Insecure.SHA1>.authenticationCode(for: hostData, using: SymmetricKey(data: testSalt))
        let hmacData = Data(hmac)
        
        // HMAC-SHA1 always produces 20 bytes (160 bits)
        #expect(hmacData.count == 20, "HMAC-SHA1 should produce 20 bytes")
    }
}