import Testing
@testable import SwiftKeyGen
import Foundation

/// Integration tests for parsing private keys generated by ssh-keygen.
///
/// These tests ensure bidirectional compatibility: we can parse and extract
/// correct public keys, comments, and metadata from keys created by OpenSSH's
/// ssh-keygen tool.
@Suite("Parse ssh-keygen Generated Keys", .tags(.integration))
struct ParseSSHKeygenKeysIntegrationTests {
    
    // MARK: - Ed25519 Keys
    
    @Test("Parse ssh-keygen Ed25519 private key (no passphrase)")
    func testParseSSHKeygenEd25519Unencrypted() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let keyPath = tempDir.appendingPathComponent("id_ed25519")
            let comment = "test-ed25519-parse@example.com"
            
            // Generate key with ssh-keygen
            let genResult = try IntegrationTestSupporter.runSSHKeygen([
                "-t", "ed25519",
                "-f", keyPath.path,
                "-N", "",  // No passphrase
                "-C", comment
            ])
            
            #expect(genResult.succeeded, "ssh-keygen should generate Ed25519 key")
            
            // Parse with our implementation
            let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: nil)
            
            // Verify key type
            #expect(key is Ed25519Key, "Parsed key should be Ed25519Key")
            
            // Verify public key matches
            let ourPublicKey = key.publicKeyString()
            let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
            
            let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
            let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
            #expect(ourNormalized == theirNormalized, "Public keys should match exactly")
            
            // Verify comment is preserved
            #expect(ourPublicKey.contains(comment), "Comment should be preserved")
        }
    }
    
    @Test("Parse ssh-keygen Ed25519 private key (with passphrase)", .tags(.slow))
    func testParseSSHKeygenEd25519Encrypted() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let keyPath = tempDir.appendingPathComponent("id_ed25519_encrypted")
            let passphrase = "test-passphrase-123"
            let comment = "encrypted-ed25519@example.com"
            
            // Generate encrypted key with ssh-keygen
            let genResult = try IntegrationTestSupporter.runSSHKeygen([
                "-t", "ed25519",
                "-f", keyPath.path,
                "-N", passphrase,
                "-C", comment
            ])
            
            #expect(genResult.succeeded, "ssh-keygen should generate encrypted Ed25519 key")
            
            // Parse with correct passphrase
            let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: passphrase)
            #expect(key is Ed25519Key, "Parsed key should be Ed25519Key")
            
            // Verify public key matches
            let ourPublicKey = key.publicKeyString()
            let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
            
            let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
            let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
            #expect(ourNormalized == theirNormalized, "Public keys should match")
            
            // Verify comment
            #expect(ourPublicKey.contains(comment), "Comment should be preserved")
            
            // Verify wrong passphrase fails
            #expect(throws: Error.self) {
                try KeyManager.readPrivateKey(from: keyPath.path, passphrase: "wrong-passphrase")
            }
        }
    }
    
    // MARK: - RSA Keys
    
    @Test("Parse ssh-keygen RSA 2048 private key (no passphrase)", .tags(.rsa))
    func testParseSSHKeygenRSA2048Unencrypted() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let keyPath = tempDir.appendingPathComponent("id_rsa_2048")
            let comment = "rsa-2048-parse@example.com"
            
            let genResult = try IntegrationTestSupporter.runSSHKeygen([
                "-t", "rsa",
                "-b", "2048",
                "-f", keyPath.path,
                "-N", "",
                "-C", comment
            ])
            
            #expect(genResult.succeeded, "ssh-keygen should generate RSA 2048 key")
            
            let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: nil)
            #expect(key is RSAKey, "Parsed key should be RSAKey")
            
            // Verify public key matches
            let ourPublicKey = key.publicKeyString()
            let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
            
            let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
            let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
            #expect(ourNormalized == theirNormalized, "Public keys should match")
            
            #expect(ourPublicKey.contains(comment), "Comment should be preserved")
        }
    }

    @Test("Parse ssh-keygen RSA 3072 private key (no passphrase)", .tags(.rsa))
    func testParseSSHKeygenRSA3072Unencrypted() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let keyPath = tempDir.appendingPathComponent("id_rsa_3072")
            let comment = "rsa-3072-parse@example.com"
            
            let genResult = try IntegrationTestSupporter.runSSHKeygen([
                "-t", "rsa",
                "-b", "3072",
                "-f", keyPath.path,
                "-N", "",
                "-C", comment
            ])
            
            #expect(genResult.succeeded, "ssh-keygen should generate RSA 3072 key")
            
            let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: nil)
            #expect(key is RSAKey, "Parsed key should be RSAKey")
            
            let ourPublicKey = key.publicKeyString()
            let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
            
            let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
            let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
            #expect(ourNormalized == theirNormalized, "Public keys should match")
            
            #expect(ourPublicKey.contains(comment), "Comment should be preserved")
        }
    }

    @Test("Parse ssh-keygen RSA 4096 private key (no passphrase)", .tags(.rsa))
    func testParseSSHKeygenRSA4096Unencrypted() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let keyPath = tempDir.appendingPathComponent("id_rsa_4096")
            let comment = "rsa-4096-parse@example.com"
            
            let genResult = try IntegrationTestSupporter.runSSHKeygen([
                "-t", "rsa",
                "-b", "4096",
                "-f", keyPath.path,
                "-N", "",
                "-C", comment
            ])
            
            #expect(genResult.succeeded, "ssh-keygen should generate RSA 4096 key")
            
            let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: nil)
            #expect(key is RSAKey, "Parsed key should be RSAKey")
            
            let ourPublicKey = key.publicKeyString()
            let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
            
            let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
            let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
            #expect(ourNormalized == theirNormalized, "Public keys should match")
            
            #expect(ourPublicKey.contains(comment), "Comment should be preserved")
        }
    }

    @Test("Parse ssh-keygen RSA 2048 private key (with passphrase)", .tags(.rsa))
    func testParseSSHKeygenRSAEncrypted() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let keyPath = tempDir.appendingPathComponent("id_rsa_encrypted")
            let passphrase = "secure-rsa-pass"
            let comment = "encrypted-rsa@example.com"
            
            let genResult = try IntegrationTestSupporter.runSSHKeygen([
                "-t", "rsa",
                "-b", "2048",
                "-f", keyPath.path,
                "-N", passphrase,
                "-C", comment
            ])
            
            #expect(genResult.succeeded, "ssh-keygen should generate encrypted RSA key")
            
            // Parse with correct passphrase
            let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: passphrase)
            #expect(key is RSAKey, "Parsed key should be RSAKey")
            
            let ourPublicKey = key.publicKeyString()
            let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
            
            let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
            let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
            #expect(ourNormalized == theirNormalized, "Public keys should match")
            
            #expect(ourPublicKey.contains(comment), "Comment should be preserved")
            
            // Verify wrong passphrase fails
            #expect(throws: Error.self) {
                try KeyManager.readPrivateKey(from: keyPath.path, passphrase: "wrong")
            }
        }
    }
    
    // MARK: - ECDSA Keys
    
    @Test("Parse ssh-keygen ECDSA P-256 private key (no passphrase)")
    func testParseSSHKeygenECDSAP256Unencrypted() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let keyPath = tempDir.appendingPathComponent("id_ecdsa_p256")
            let comment = "ecdsa-p256-parse@example.com"
            
            let genResult = try IntegrationTestSupporter.runSSHKeygen([
                "-t", "ecdsa",
                "-b", "256",
                "-f", keyPath.path,
                "-N", "",
                "-C", comment
            ])
            
            #expect(genResult.succeeded, "ssh-keygen should generate ECDSA P-256 key")
            
            let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: nil)
            #expect(key is ECDSAKey, "Parsed key should be ECDSAKey")
            
            let ecdsaKey = key as! ECDSAKey
            #expect(ecdsaKey.keyType == .ecdsa256, "Key type should be ecdsa256")
            
            let ourPublicKey = key.publicKeyString()
            let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
            
            let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
            let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
            #expect(ourNormalized == theirNormalized, "Public keys should match")
            
            #expect(ourPublicKey.contains(comment), "Comment should be preserved")
        }
    }
    
    @Test("Parse ssh-keygen ECDSA P-384 private key (no passphrase)")
    func testParseSSHKeygenECDSAP384Unencrypted() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let keyPath = tempDir.appendingPathComponent("id_ecdsa_p384")
            let comment = "ecdsa-p384-parse@example.com"
            
            let genResult = try IntegrationTestSupporter.runSSHKeygen([
                "-t", "ecdsa",
                "-b", "384",
                "-f", keyPath.path,
                "-N", "",
                "-C", comment
            ])
            
            #expect(genResult.succeeded, "ssh-keygen should generate ECDSA P-384 key")
            
            let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: nil)
            #expect(key is ECDSAKey, "Parsed key should be ECDSAKey")
            
            let ecdsaKey = key as! ECDSAKey
            #expect(ecdsaKey.keyType == .ecdsa384, "Key type should be ecdsa384")
            
            let ourPublicKey = key.publicKeyString()
            let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
            
            let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
            let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
            #expect(ourNormalized == theirNormalized, "Public keys should match")
            
            #expect(ourPublicKey.contains(comment), "Comment should be preserved")
        }
    }
    
    @Test("Parse ssh-keygen ECDSA P-521 private key (no passphrase)")
    func testParseSSHKeygenECDSAP521Unencrypted() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let keyPath = tempDir.appendingPathComponent("id_ecdsa_p521")
            let comment = "ecdsa-p521-parse@example.com"
            
            let genResult = try IntegrationTestSupporter.runSSHKeygen([
                "-t", "ecdsa",
                "-b", "521",
                "-f", keyPath.path,
                "-N", "",
                "-C", comment
            ])
            
            #expect(genResult.succeeded, "ssh-keygen should generate ECDSA P-521 key")
            
            let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: nil)
            #expect(key is ECDSAKey, "Parsed key should be ECDSAKey")
            
            let ecdsaKey = key as! ECDSAKey
            #expect(ecdsaKey.keyType == .ecdsa521, "Key type should be ecdsa521")
            
            let ourPublicKey = key.publicKeyString()
            let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
            
            let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
            let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
            #expect(ourNormalized == theirNormalized, "Public keys should match")
            
            #expect(ourPublicKey.contains(comment), "Comment should be preserved")
        }
    }
    
    @Test("Parse ssh-keygen ECDSA P-256 private key (with passphrase)", .tags(.slow))
    func testParseSSHKeygenECDSAEncrypted() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let keyPath = tempDir.appendingPathComponent("id_ecdsa_encrypted")
            let passphrase = "ecdsa-secure-123"
            let comment = "encrypted-ecdsa@example.com"
            
            let genResult = try IntegrationTestSupporter.runSSHKeygen([
                "-t", "ecdsa",
                "-b", "256",
                "-f", keyPath.path,
                "-N", passphrase,
                "-C", comment
            ])
            
            #expect(genResult.succeeded, "ssh-keygen should generate encrypted ECDSA key")
            
            // Parse with correct passphrase
            let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: passphrase)
            #expect(key is ECDSAKey, "Parsed key should be ECDSAKey")
            
            let ourPublicKey = key.publicKeyString()
            let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
            
            let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
            let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
            #expect(ourNormalized == theirNormalized, "Public keys should match")
            
            #expect(ourPublicKey.contains(comment), "Comment should be preserved")
            
            // Verify wrong passphrase fails
            #expect(throws: Error.self) {
                try KeyManager.readPrivateKey(from: keyPath.path, passphrase: "wrong")
            }
        }
    }
    
    // MARK: - Comment Preservation
    
    @Test("Preserve keys with unusual comments")
    func testPreserveUnusualComments() throws {
        try IntegrationTestSupporter.withTemporaryDirectory { tempDir in
            let unusualComments = [
                "user@host.example.com",
                "Test Key 🔑",
                "multi word comment with spaces",
                "email+tag@example.com",
                ""  // Empty comment
            ]
            
            for (index, comment) in unusualComments.enumerated() {
                let keyPath = tempDir.appendingPathComponent("key_\(index)")
                
                let genResult = try IntegrationTestSupporter.runSSHKeygen([
                    "-t", "ed25519",
                    "-f", keyPath.path,
                    "-N", "",
                    "-C", comment
                ])
                
                #expect(genResult.succeeded, "ssh-keygen should generate key with comment: \(comment)")
                
                let key = try KeyManager.readPrivateKey(from: keyPath.path, passphrase: nil)
                let ourPublicKey = key.publicKeyString()
                
                if !comment.isEmpty {
                    #expect(ourPublicKey.contains(comment), "Comment '\(comment)' should be preserved")
                }
                
                // Verify public key matches
                let sshPublicKey = try String(contentsOf: keyPath.appendingPathExtension("pub"), encoding: .utf8)
                let ourNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(ourPublicKey)
                let theirNormalized = IntegrationTestSupporter.normalizeOpenSSHPublicKey(sshPublicKey)
                #expect(ourNormalized == theirNormalized, "Public keys should match for comment: \(comment)")
            }
        }
    }
}
