import Testing
@testable import SwiftKeyGen
import Foundation
import Crypto

@Test("Test HMAC-SHA1 hashing compatibility with ssh-keygen -H")
func testHashingCompatibility() throws {
    // Test vectors from OpenSSH
    // These are actual hashed entries generated by ssh-keygen -H
    
    // Test 1: Simple hostname (generated by ssh-keygen -H)
    let hostname1 = "github.com"
    let hashedEntry1 = "|1|HaNPCCkur6qYZXCzIppl/TodLqw=|GgFFFoJPMiwE59VjqulA59RWQxc="
    
    let manager = KnownHostsManager(filePath: "/tmp/test_known_hosts")
    
    // Verify our implementation can verify ssh-keygen generated hashes
    #expect(manager.verifyHashedHost(hashedEntry1, hostname: hostname1) == true)
    #expect(manager.verifyHashedHost(hashedEntry1, hostname: "wrong.com") == false)
    
    // Test 2: Hostname with port (generated by ssh-keygen -H)
    let hostname2 = "[example.com]:2222"
    let hashedEntry2 = "|1|MqPW9+kMObMEhin7KtSezLHs0qc=|RsILfjmyLGY39C38uK65QInDmMc="
    
    #expect(manager.verifyHashedHost(hashedEntry2, hostname: hostname2) == true)
    #expect(manager.verifyHashedHost(hashedEntry2, hostname: "example.com") == false)
    
    // Test 3: IP address (generated by ssh-keygen -H)
    let hostname3 = "192.168.1.1"
    let hashedEntry3 = "|1|O1R3WUmACW3NL3xeF5XWKf4PuhA=|Ro4TK7ueLhcepbg5rjnYDG4NL1c="
    
    #expect(manager.verifyHashedHost(hashedEntry3, hostname: hostname3) == true)
}

@Test("Test hash generation matches ssh-keygen format")
func testHashGeneration() throws {
    let manager = KnownHostsManager(filePath: "/tmp/test_known_hosts")
    
    // Test that our hash format matches expected format
    let hostname = "test.example.com"
    let hashed = manager.hashHostname(hostname)
    
    // Verify format: |1|base64_salt|base64_hash
    #expect(hashed.hasPrefix("|1|"))
    let components = hashed.split(separator: "|")
    #expect(components.count == 3) // "1", salt, hash (split doesn't include empty before first |)
    
    // Verify salt and hash are valid base64
    let salt = String(components[1])
    let hash = String(components[2])
    #expect(Data(base64Encoded: salt) != nil)
    #expect(Data(base64Encoded: hash) != nil)
    
    // Verify salt is 20 bytes (SHA1 length)
    #expect(Data(base64Encoded: salt)?.count == 20)
    
    // Verify we can verify our own hashes
    #expect(manager.verifyHashedHost(hashed, hostname: hostname) == true)
    #expect(manager.verifyHashedHost(hashed, hostname: "wrong.com") == false)
}

@Test("Test comma-separated host patterns")
func testCommaSeparatedHosts() throws {
    let tempFile = "/tmp/test_known_hosts_\(UUID().uuidString)"
    let manager = KnownHostsManager(filePath: tempFile)
    defer { try? FileManager.default.removeItem(atPath: tempFile) }
    
    // Create entry with multiple hostnames
    let entry = KnownHostsEntry(
        hostPattern: "host1.com,host2.com,192.168.1.1",
        keyType: .ed25519,
        publicKey: Data([1, 2, 3]) // Some dummy data
    )
    
    try manager.addEntry(entry)
    
    // Hash the file
    try manager.hashHostnames()
    
    // Read back and verify all patterns are hashed
    let hashedEntries = try manager.readEntries()
    #expect(hashedEntries.count == 1)
    
    let hashedPatterns = hashedEntries[0].hostPattern.split(separator: ",").map(String.init)
    #expect(hashedPatterns.count == 3)
    
    // All should be hashed
    for pattern in hashedPatterns {
        #expect(pattern.hasPrefix("|1|"))
    }
}

@Test("Test wildcard pattern matching")
func testWildcardMatching() throws {
    let manager = KnownHostsManager(filePath: "/tmp/test")
    
    // Test wildcards
    #expect(manager.matchesWildcardPattern("*.github.com", hostname: "api.github.com") == true)
    #expect(manager.matchesWildcardPattern("*.github.com", hostname: "github.com") == false)
    #expect(manager.matchesWildcardPattern("192.168.1.*", hostname: "192.168.1.100") == true)
    #expect(manager.matchesWildcardPattern("192.168.1.*", hostname: "192.168.2.100") == false)
    
    // Test ? wildcard
    #expect(manager.matchesWildcardPattern("host?.com", hostname: "host1.com") == true)
    #expect(manager.matchesWildcardPattern("host?.com", hostname: "host10.com") == false)
    
    // Test bracketed format with port
    #expect(manager.matchesWildcardPattern("[*.example.com]:22", hostname: "[test.example.com]:22") == true)
    #expect(manager.matchesWildcardPattern("[*.example.com]:22", hostname: "[test.example.com]:2222") == false)
}

// Extension to expose private methods for testing
extension KnownHostsManager {
    func verifyHashedHost(_ hashedPattern: String, hostname: String) -> Bool {
        // Parse |1|salt|hash format
        let components = hashedPattern.split(separator: "|").map(String.init)
        guard components.count >= 3 else {
            return false
        }
        
        // Components will be ["1", "salt", "hash"] - split removes empty elements
        guard components[0] == "1",
              let salt = Data(base64Encoded: components[1]),
              let expectedHash = Data(base64Encoded: components[2]) else {
            return false
        }
        
        // Compute HMAC for hostname with given salt
        let hostData = Data(hostname.utf8)
        let hmac = HMAC<Insecure.SHA1>.authenticationCode(for: hostData, using: SymmetricKey(data: salt))
        
        return Data(hmac) == expectedHash
    }
    
    func hashHostname(_ hostname: String) -> String {
        // Generate random salt
        let salt = Data((0..<20).map { _ in UInt8.random(in: 0...255) })
        
        // Hash hostname with salt using HMAC-SHA1
        let hostData = Data(hostname.utf8)
        let hmac = HMAC<Insecure.SHA1>.authenticationCode(for: hostData, using: SymmetricKey(data: salt))
        
        // Format: |1|base64(salt)|base64(hash)
        return "|1|\(salt.base64EncodedString())|\(Data(hmac).base64EncodedString())"
    }
    
    func matchesWildcardPattern(_ pattern: String, hostname: String) -> Bool {
        // Convert shell-style wildcards to regex
        var regexPattern = pattern
            .replacingOccurrences(of: ".", with: "\\.")
            .replacingOccurrences(of: "*", with: ".*")
            .replacingOccurrences(of: "?", with: ".")
        
        // Handle bracketed format [hostname]:port
        if pattern.hasPrefix("[") && pattern.contains("]:") {
            regexPattern = regexPattern
                .replacingOccurrences(of: "[", with: "\\[")
                .replacingOccurrences(of: "]", with: "\\]")
        }
        
        regexPattern = "^" + regexPattern + "$"
        
        guard let regex = try? NSRegularExpression(pattern: regexPattern, options: []) else {
            return false
        }
        
        let range = NSRange(location: 0, length: hostname.utf16.count)
        return regex.firstMatch(in: hostname, options: [], range: range) != nil
    }
}